export const ADD_LISTINGS = "ADD_LISTINGS";
export const LISTINGS_LOADING = "LISTINGS_LOADING";
export const LISTINGS_FAILED = "LISTINGS_FAILED";
export const ADD_PROFILES = "ADD_PROFILES";
export const PROFILES_LOADING = "PROFILES_LOADING";
export const PROFILES_FAILED = "PROFILES_FAILED";